spring:
  application:
    name: l7-fc-mockservices
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:avisdb;DB_CLOSE_DELAY=-1
    username: avis
    password: avis
    driverClassName: org.h2.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


server:
  port: 8011

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
